@startuml Diagram
left to right direction
actor "Студент" as Student
actor "Сотрудник склада" as Stockman

rectangle "Система учёта спортивной формы" {
    Student --> (Просматривать список выданной формы)
    Student -- (Просматривать сроки возврата)
    Student -- (Просматривать информацию о компенсациях)
    Student -- (Авторизоваться)
    
    Stockman -- (Авторизоваться)
    Stockman -- (Просматривать справочник формы)
    Stockman -- (Просматривать остатки на складе)
    Stockman -- (Выдавать спортивную форму)
    Stockman -- (Формировать отчёты)
    Stockman -- (Оценивать состояние формы)
    Stockman -- (Принимать возврат формы)
    Stockman -- (Рассчитывать компенсацию)
    Stockman -- (Регистрировать утрату/повреждение)
    Stockman -- (Просматривать справочник студентов)
    
    (Принимать возврат формы) .> (Оценивать состояние формы) : <<include>>
    (Рассчитывать компенсацию) .> (Оценивать состояние формы) : <<include>>
}

@enduml